### ISSUE TITLE
juju-resources fails verification when files have the same name

### ISSUE THREAD

**Issue by kwmonroe** [juju-solutions/jujuresources#8]
We have hadoop-2.4.1.tgz for x86_64 and aarch64.  When fetching --all resources from a resources.yaml, juju-resources gives an "invalid" error for aarch64 because the x86_64 tarball has the same base name.

juju-resources should handle the case when multiple resources have the same base filename.

**Comment by bcsaller** [comment]
If you have the SHA doesn't it make sense to use that name?

**Comment by johnsca** [comment]
I went with using the resource name because we apparently support URLs for remote hashes, though I'm not sure it's being used at the moment.  It also matches a bit better with how Python resources are handled.

TBH, it would be great to scrap the whole mirror thing in favor of something more robust using existing mirror packages, as Adam had been discussing.
